image:
  tag: 0.1
  repository: "corelab/ks-guestbook-demo"
  pullPolicy: "Always"
ingress:
  path: "/"
  hosts:
  - "chart-example.local"
  annotations: {}
  tls: []
  enabled: false
replicaCount: 4
tolerations: []
service:
  port: 80
  type: "ClusterIP"
resources: {}
nodeSelector: {}
affinity: {}
